### ISSUE TITLE
Angular-5 competablity 

### ISSUE THREAD

**Issue by abbasarbi** [CanKattwinkel/angular-2-animation-tutorial#3]
:host is not working in angular 5, can you please update this according to angular 5.

**Comment by CanKattwinkel** [comment]
@abbasarbi `:host` is not deprecated and working in Angular 5. See https://angular.io/guide/component-styles 

Maybe you have set your `encapsulation` to `ViewEncapsulation.None` then it wont work and you have to use the element selector instead.

**Comment by abbasarbi** [comment]
Thanks, i have changed it to **ViewEncapsulation.Emulated** is it ok?
